 name: First workflow
 on: workflow_dispatch
 jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
       - name: Print greeting
         run: echo "hello"
       - name: Print secret
         run: echo "${{ secrets.SECRET1 }}"
       - name: Checkout repository
         uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
          python-version: '3.9'
       - name: Run script
         env:
          USERNAME: "berfin123"
         run: python folder/main.py
         

