 name: First workflow
 on: workflow_dispatch
 jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
       - name: Print greeting
         run: echo "hello"
       - name: Print secret
         run: echo "${{ secrets.SECRET1 }}"
       - name: Checkout repository
         uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
          python-version: '3.9'
       - name: Run script
         env:
          USER_NAME: ${{ secrets.SECRET1 }}
         run: python main.py
   pylint:
    name: pylint
    runs-on: Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analyzing the code with pylint
        run: |
          pylint --fail-under=7 $(git ls-files '*.py')
         

